version: "1.5"

only:
  triggerType:
    - push
    - pullRequest
  triggerBranch:
    prTargetBranch:
      - ^master$
    pushOriginalBranch:
      - ^master$

parameters:
  image: reg.docker.alibaba-inc.com/tbase/tbase:dev-20230605-clang13
      
stages:
  - FORMAT-PRE-CHECK
  - BUILD_UT

format-pre-check:
  stage: FORMAT-PRE-CHECK
  aciTags: DOCKER
  steps:
    - plugin: clone
    - plugin: shell
      inputs:
        image: ${image}
        command:
        - |
          make format
          if [[ -n $(git status --porcelain) ]]; then
              exit 1
          fi
  
vsag_build_ut:
  stage: BUILD_UT
  agent:
    #resourceClass: S #2C4G
    resourceClass: M #4C8G
    #resourceClass: L #8C16G
  steps:
    # - plugin: clone
    - plugin: shell
      inputs:
        image: ${image}
        command:
        - |
          echo "clone source codes..."
          git clone http://ice_test:${ACI_VAR_ICE_CODE_PASSWORD}@gitlab.alipay-inc.com/octopus/vsag.git
          cd vsag
          git checkout -b ${ACI_COMMIT_REF_NAME} origin/${ACI_COMMIT_REF_NAME}
          git fetch --tags
          #
          echo "running unittests..."
          sh ./scripts/deps/install_deps_centos.sh
          #
          # download ccache
          osscmd config --host=${OSS_HOST} --id=${OSS_ACCESS_KEY_ID} --key=${OSS_ACCESS_KEY_SECRET}
          osscmd get oss://tbase/vsag/ccache.tar.gz ./ccache.tar.gz
          mkdir $HOME/.ccache
          tar -xzf ./ccache.tar.gz -C $HOME
          #
          # compile
          export CC=/usr/bin/gcc
          export CXX=/usr/bin/g++
          export PATH=/usr/lib/ccache:$PATH
          make test
          #
          # upload ccache
          cd $HOME/ && tar -czf ccache.tar.gz .ccache
          osscmd put ./ccache.tar.gz oss://tbase/vsag/ccache.tar.gz  > /dev/null 2>&1
  timeout: 60
  allowFailure: false
