version: "1.5"

only:
  triggerType:
    - push
    - pullRequest
  triggerBranch:
    prTargetBranch:
      - ^master$
    pushOriginalBranch:
      - ^master$

parameters:
  image: reg.docker.alibaba-inc.com/tbase/tbase:dev-20230605-clang13
  image_gcc: reg.docker.alibaba-inc.com/tbase/tbase:dev-20230605-gcc10
  image_vsag: reg.docker.alibaba-inc.com/tbase/tbase:dev-20230605-vsag

stages:
  - FORMAT-PRE-CHECK
  - BUILD_UT

format-pre-check:
  stage: FORMAT-PRE-CHECK
  aciTags: DOCKER
  steps:
    - plugin: clone
    - plugin: shell
      inputs:
        image: ${image}
        command:
        - |
          make format
          if [[ -n $(git status --porcelain) ]]; then
              exit 1
          fi

vsag_build_ut_cov:
  stage: BUILD_UT
  agent:
    #resourceClass: S #2C4G
    resourceClass: M #4C8G
    #resourceClass: L #8C16G
  steps:
    # - plugin: clone
    - plugin: shell
      inputs:
        image: ${image_vsag}
        command:
        - |
          echo "clone source codes..."
          git clone http://ice_test:${ACI_VAR_ICE_CODE_PASSWORD}@gitlab.alipay-inc.com/octopus/vsag.git
          cd vsag
          git checkout ${ACI_COMMIT_REF_NAME}
          git fetch --tags
          #
          echo "running unittests..."
          osscmd config --host=${OSS_HOST} --id=${OSS_ACCESS_KEY_ID} --key=${OSS_ACCESS_KEY_SECRET}
          #
          # download ccache
          bash scripts/misc/ccache.sh
          #
          # compile
          export PATH=/usr/lib/ccache:$PATH
          make test_cov
          #
  timeout: 60
  allowFailure: false

vsag_build_asan_ut:
  stage: BUILD_UT
  agent:
    #resourceClass: S #2C4G
    resourceClass: M #4C8G
    #resourceClass: L #8C16G
  steps:
    # - plugin: clone
    - plugin: shell
      inputs:
        image: ${image_vsag}
        command:
        - |
          echo "clone source codes..."
          git clone http://ice_test:${ACI_VAR_ICE_CODE_PASSWORD}@gitlab.alipay-inc.com/octopus/vsag.git
          cd vsag
          git checkout ${ACI_COMMIT_REF_NAME}
          git fetch --tags
          #
          echo "running unittests..."
          osscmd config --host=${OSS_HOST} --id=${OSS_ACCESS_KEY_ID} --key=${OSS_ACCESS_KEY_SECRET}
          #
          # download ccache
          bash scripts/misc/ccache.sh
          #
          # compile
          export PATH=/usr/lib/ccache:$PATH
          make test_asan
          #
    - plugin: memcheck-log-parser
      inputs:
        tools: "asan ubsan"
        log_file_path: "testresult/"
        upload: "true"
      outputs:
        - memory_check_error
  timeout: 60
  allowFailure: false
